<div class="sidebarFooter">
	<div class="footerLine">
		<div class="floatLeft">
			<div class="footerLink">
				<a href="{{ABOUT_URL}}">About</a>
			</div>

				<span class="separator">-</span>

			<div class="footerLink">
				<a href="#">More <i class="fa fa-caret-up"></i></a>

				<div class="dropup dropupLeft">
					<a href="{{CONTACT_URL}}">Contact</a>
					<a href="{{PRIVACY_URL}}">Privacy</a>
					<a href="{{DISCLAIMER_URL}}">Disclaimer</a>
					<a href="{{DEVELOPERS_URL}}">Developers</a>
				</div>
			</div>
		</div>

		<div class="floatRight">
			<div class="footerLink">
				<i class="fa fa-language"></i> <a>Languages <i class="fa fa-caret-up"></i></a>
				<div class="dropup dropupRight">
					{{LANGUAGES}}
				</div>
			</div>
		</div>

		<div class="floatClear"></div>
	</div>

	<div class="footerLine">
		Copyright <i class="fa fa-copyright"></i> {{YEAR}} {{CONFIG_SITE_NAME}}. All rights reserved.
	</div>
</div>