<div class="userColumn suggestion_{{LIST_EVENT_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_EVENT_URL}}" data-href="?a=timeline&id={{LIST_EVENT_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_EVENT_THUMBNAIL_URL}}" alt="{{LIST_EVENT_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_EVENT_URL}}" data-href="?a=timeline&id={{LIST_EVENT_USERNAME}}">{{LIST_EVENT_NAME}}</a>
        </strong>

        <small>{{LIST_EVENT_TIME}}</small>
        <small>{{LIST_EVENT_LOCATION}}</small>
        <small><i class="fa fa-{{EVENT_STATUS_ICON}}"></i> {{EVENT_STATUS}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_EVENT_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>