<div class="album-edit-data">
    <div class="album-name-header">
        <input class="album_name" type="text" value="{{ALBUM_NAME}}">
    </div>

    <p class="album-descr-para">
        <textarea class="auto-grow-input album_descr">{{ALBUM_DESCR}}</textarea>
        <button class="active" onclick="saveAlbumChanges();">Save Changes</button>
        <input type="hidden" class="album_id" value="{{ALBUM_ID}}">
    </p>
</div>