<div class="listJar">
    <div class="multiTabJar">
        <div class="boldTab"><i class="ski ski-friends"></i> {{FOLLOWING_HEADER_LABEL}}</div>
    </div>

    <div class="list-followings">
    	{{LIST_FOLLOWINGS}}
    </div>

    <a class="infoColumn view-more-anchor hide" align="center" onclick="listFollowings();">
    	@view_more@
    </a>
</div>
<script>
$(function(){
	if ($(".list-followings").find(".userColumn").length > 0)
	{
		$(".view-more-anchor").removeClass("hide");
	}
});

function listFollowings() {
	lastFollowId = $(".list-followings").find(".userColumn:last").attr('data-user-id');
	$.get(
		Sk_requestPath(),
		{
			t: "user",
			a: "list_followings",
			timeline_id: {{TIMELINE_ID}},
			before_id: lastFollowId
		},
		function(data)
		{
			if (data.status == 200)
			{
				if (data.html.length > 0)
				{
					$(".list-followings").append(data.html);
				}
				else
				{
					$(".view-more-anchor").hide();
				}
			}
		}
	);
}
</script>