<div class="userColumn suggestion_{{LIST_FOLLOWING_ID}}" data-user-id="{{LIST_FOLLOWING_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_FOLLOWING_URL}}" data-href="?a=timeline&id={{LIST_FOLLOWING_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_FOLLOWING_THUMBNAIL_URL}}" alt="{{LIST_FOLLOWING_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_FOLLOWING_URL}}" data-href="?a=timeline&id={{LIST_FOLLOWING_USERNAME}}">{{LIST_FOLLOWING_NAME}}</a>
        </strong>

        <small>{{LIST_FOLLOWING_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_FOLLOWING_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>