<div class="userColumn suggestion_{{LIST_PAGE_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_PAGE_URL}}" data-href="?a=timeline&id={{LIST_PAGE_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_PAGE_THUMBNAIL_URL}}" alt="{{LIST_PAGE_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_PAGE_URL}}" data-href="?a=timeline&id={{LIST_PAGE_USERNAME}}">{{LIST_PAGE_NAME}}</a>
        </strong>

        <small>{{LIST_PAGE_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_PAGE_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>