<td class="statistic" align="center" valign="middle">
    <a href="{{FOLLOWING_TAB_URL}}" data-href="?a=timeline&b=following&id={{TIMELINE_USERNAME}}">
        {{FOLLOWING_NUM}} @following_label@
    </a>
</td>

<td class="statistic" align="center" valign="middle">
    <a href="{{FOLLOWERS_TAB_URL}}" data-href="?a=timeline&b=followers&id={{TIMELINE_USERNAME}}">
        {{FOLLOWERS_NUM}} @followers_label@
    </a>
</td>