<a class="accept-{{LIST_REQUEST_ID}}" onclick="SK_acceptFollowRequest({{LIST_REQUEST_ID}});">
    <i id="acceptBtn{{LIST_REQUEST_ID}}" data-icon="check" class="fa fa-check progress-icon"></i> @accept@ 
</a>
<a class="decline-{{LIST_REQUEST_ID}}" onclick="SK_declineFollowRequest({{LIST_REQUEST_ID}});">
    <i id="declineBtn{{LIST_REQUEST_ID}}" data-icon="circle-o" class="fa fa-circle-o progress-icon"></i> @decline@ 
</a>