<div class="timeline-buttons">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        {{FOLLOW_BUTTON_HTML}}

        {{MESSAGE_BUTTON_HTML}}

        <td align="center" valign="middle">
            <a onclick="Sk_blockUserPopup();">
                <i class="ski ski-user-minus" data-icon="user-minus"></i>
                <span>@block@</span>
            </a>
        </td>
    </tr>
    </table>
</div>
<script>
function Sk_blockUserPopup()
{
	$.ajax({
        type: 'GET',
        url: Sk_requestPath(),
        data: {
            t: "user",
            a: "block_popup",
            id: {{TIMELINE_ID}}
        },
        dataType: "json",
        beforeSend: function()
        {
            iconProgress($(".blockBtn").find("i"));
        },
        success: function(result)
        {
            iconProgress($(".blockBtn").find("i"));
            if (result.status === 200) $(document.body).append(result.html);
        }
    });
}
</script>