<div class="userColumn group-admin-{{LIST_ADMIN_USER_ID}}" data-user-id="{{LIST_ADMIN_USER_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_ADMIN_USER_URL}}" data-href="?a=timeline&id={{LIST_ADMIN_USER_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_ADMIN_USER_THUMBNAIL_URL}}" alt="{{LIST_ADMIN_USER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_ADMIN_USER_URL}}" data-href="?a=timeline&id={{LIST_ADMIN_USER_USERNAME}}">{{LIST_ADMIN_USER_NAME}}</a>
        </strong>

        <small>{{LIST_ADMIN_USER_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_ADMINS_BTN}}
    </div>

    <div class="floatClear"></div>
</div>