<div class="userColumn group-member-{{LIST_MEMBER_USER_ID}}" data-user-id="{{LIST_MEMBER_USER_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_MEMBER_USER_URL}}" data-href="?a=timeline&id={{LIST_MEMBER_USER_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_MEMBER_USER_THUMBNAIL_URL}}" alt="{{LIST_MEMBER_USER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_MEMBER_USER_URL}}" data-href="?a=timeline&id={{LIST_MEMBER_USER_USERNAME}}">{{LIST_MEMBER_USER_NAME}}</a>
        </strong>

        <small>{{LIST_MEMBER_USER_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_MEMBER_USER_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>