<form class="update-timeline-form" method="post">
    <div class="form-container">
        <div class="multiTabJar">
            <div class="boldTab">
                <i class="fa fa-key"></i>
                @update_password_label@
            </div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @current_password_label@:
            </label>

            <div class="input floatLeft">
                <input type="password" name="current_password">
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @new_password_label@:
            </label>

            <div class="input floatLeft">
                <input type="text" name="new_password">
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <button class="active">
                <i id="updatePasswordSettingsIcon" class="fa fa-lightbulb progress-icon hide"></i>
                @save_changes_button@
            </button>
        </div>
    </div>
</form>

<script>
$(function(){
    $('form.update-timeline-form').ajaxForm({
        url: Sk_requestPath()+'?t=user&a=settings',

        beforeSend: function(){
            iconProgress($("#updatePasswordSettingsIcon"));
        },
        
        success: function (responseText)
        {
            iconProgress($("#updatePasswordSettingsIcon"));
            if (responseText.status === 200)
            {
                $('.update-timeline-form .multiTabJar').after('<div class="success-message">@password_updated@</div>');
                setTimeout(function(){
                    location.reload();
                }, 500);
            }
            else {
                $('.update-timeline-form .multiTabJar').after('<div class="success-message hidden">@passwords_not_match@</div>');
                $('.success-message').fadeIn('fast',function () {
                    $(this).fadeOut(1500, function() {
                        $(this).remove();
                    });
                });
            }
        }
    });
});
</script>