<div class="followLi">
	<div class="floatLeft checkJar">
		<input id="{{LI_ID}}" class="followCheck" type="checkbox" name="follow[]" value="{{LI_ID}}" checked>
		<label for="{{LI_ID}}"></label>
	</div>

	<div class="floatLeft imageJar">
		<img src="{{LI_AVATAR}}" class="borderRadius100">
	</div>

	<div class="floatLeft textJar">
		<strong>{{LI_NAME}}</strong>
		<small>@{{LI_USERNAME}}</small>
	</div>

	<div class="floatClear"></div>
</div>