<div class="floatLeft span35">
    {{TIMELINE_BUTTONS}}

    <div class="listJar">
        <div class="multiTabJar">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-info-circle"></i> @about_label@
            </div>
        </div>

        <div class="infoColumn">
            <div class="iconJar floatLeft">
                <i class="fa fa-tags"></i>
            </div>
            
            <div class="textJar floatLeft">
                {{CATEGORY_NAME}}
            </div>

            <div class="floatClear"></div>
        </div>

        {{INFO_ADDRESS_ROW}}
        
        {{INFO_AWARDS_ROW}}
        
        {{INFO_PHONE_ROW}}
        
        {{INFO_PRODUCTS_ROW}}

        {{INFO_ABOUT_ROW}}
    </div>

    {{SIDEBAR_PHOTOS}}

    {{CONFIG_AD_PLACE_TIMELINE}}
</div>