<div class="floatRight span23">
    <div class="listJar">
        <div class="multiTabJar">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-align-justify"></i>
                @menu_label@
            </div>
        </div>
        
        {{GENERAL_SETTINGS_LINK}}
        
        {{PRIVACY_SETTINGS_LINK}}

        {{EMAIL_NOTIFICATION_SETTINGS_LINK}}
        
        {{AVATAR_CHANGE_SETTINGS_LINK}}
        
        {{COVER_CHANGE_SETTINGS_LINK}}
        
        {{PASSWORD_CHANGE_SETTINGS_LINK}}

        {{BLOCKED_USERS_SETTINGS_LINK}}

        {{DEACTIVATE_SETTINGS_LINK}}
    </div>

    {{SIDEBAR_FOOTER}}
</div>