<div class="listJar groupSuggestionsJar">
    <div class="headerJar multiTabJar">
        <div class="floatLeft">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-bolt"></i> @featured_users@
            </div>
        </div>

        <div class="floatRight">
            
        </div>

        <div class="floatClear"></div>
    </div>

    <div class="featuredUsers">
        {{LI_FEATURED_USERS}}
    </div>
</div>