<form class="update-timeline-form" method="post">
    <div class="form-container">
        <div class="multiTabJar">
            <div class="boldTab">
                <i class="fa fa-gear"></i>
                @general_settings_label@
            </div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @username_label@
            </label>

            <div class="input floatLeft">
                <input type="text" name="username" value="{{USER_USERNAME}}" autocomplete="off" onkeyup="SK_checkUsername(this.value,{{USER_ID}},'.check-username-result',true);">
                <div class="check-username-result ajax-result"></div>
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @fullname_label@
            </label>

            <div class="input floatLeft">
                <input type="text" name="name" value="{{USER_NAME}}">
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @about_label@
            </label>

            <div class="input floatLeft">
                <textarea name="about" valign="top">{{USER_ABOUT}}</textarea>
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @email_label@
            </label>

            <div class="input floatLeft">
                <input type="text" name="email" value="{{USER_EMAIL}}">
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @birthday_label@
            </label>

            <div class="input floatLeft">
                <select class="birth-month-select" name="birthday[0]" style="width: 30%;" onchange="SK_getMonthDays(this.value);">
                    {{BIRTH_MONTH_OPTIONS}}
                </select>

                <select class="birth-date-select" name="birthday[1]" style="width: 20%;">
                    {{BIRTH_DATE_OPTIONS}}
                </select>

                <select class="birth-year-select" name="birthday[2]" style="width: 30%;">
                    {{BIRTH_YEAR_OPTIONS}}
                </select>
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @gender_label@
            </label>

            <div class="input floatLeft">
                <select name="gender">
                    <option value="male" {{GENDER_MALE_SELECTED_ATTR}}>
                        @gender_male_label@
                    </option>

                    <option value="female" {{GENDER_FEMALE_SELECTED_ATTR}}>
                        @gender_female_label@
                    </option>
                </select>
            </div>
            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @country@
            </label>

            <div class="input floatLeft">
                <select name="country"></select>
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @location_label@
            </label>

            <div class="input floatLeft">
                <input type="text" name="current_city" value="{{USER_LOCATION}}">
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @hometown_label@
            </label>

            <div class="input floatLeft">
                <input type="text" name="hometown" value="{{USER_HOMETOWN}}">
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <label class="floatLeft">
                @timezone@
            </label>

            <div class="input floatLeft">
                <select name="timezone">
                    {{TIMEZONE_OPTIONS}}
                </select>
            </div>

            <div class="floatClear"></div>
        </div>
        
        <div class="form-input-wrapper">
            <button class="active">
                <i id="updateGeneralSettingsIcon" class="fa fa-lightbulb progress-icon hide"></i> 
                @save_changes_button@
            </button>
        </div>
    </div>
</form>

<script>
var countries = {{COUNTRIES}};
var currentCountry = {{USER_COUNTRY_ID}};

$(function(){
    autosize($("textarea"));
    $('form.update-timeline-form').ajaxForm({
        url: Sk_requestPath()+'?t=user&a=settings',
        
        beforeSend: function()
        {
            iconProgress($("#updateGeneralSettingsIcon"));
        },
        
        success: function (responseText)
        {
            if (responseText.status === 200) location.reload();
            iconProgress($("#updateGeneralSettingsIcon"));
        }
    });

    $.each(countries, function(i,v)
    {
        $optionTag = (i == currentCountry) ? '<option value="' + i + '" selected>' + v + '</option>' : '<option value="' + i + '">' + v + '</option>';
        $('select[name="country"]').append($optionTag);
    });
});

function SK_getMonthDays(month_number) {
    var month = new Array();
    month["01"] = 31;
    month["02"] = 28;
    month["03"] = 31;
    month["04"] = 30;
    month["05"] = 31;
    month["06"] = 30;
    month["07"] = 31;
    month["08"] = 31;
    month["09"] = 30;
    month["10"] = 31;
    month["11"] = 30;
    month["12"] = 31;

    $('.birth-date-select').html('');
    
    for (i = 1; i <= month[month_number]; i++)
    {
        if (i < 10) i = "0" + i;
        $('.birth-date-select').append('<option value="'+ i +'">'+ i +'</option>');
    }
}
</script>