<form class="update-timeline-form" method="post">
    <div class="form-container">
        <div class="multiTabJar">
            <div class="boldTab">
                <i class="fa fa-lock"></i>
                @privacy_settings_label@
            </div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @birthday_visibility@:
            </label>

            <div class="input floatLeft">
                <select name="birthday_visibility">
                    <option value="month_date_and_year">
                        @month_date_and_year@
                    </option>

                    <option value="month_and_date">
                        @month_and_date@
                    </option>

                    <option value="none">
                        @none@
                    </option>
                </select>
            </div>

            <div class="floatClear"></div>
        </div>
        
        {{FOLLOW_PRIVACY_ROWS}}

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @message_privacy_label@:
            </label>

            <div class="input floatLeft">
                <select name="message_privacy">
                    <option value="everyone" {{MESSAGE_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @everyone@
                    </option>

                    <option value="following" {{MESSAGE_PRIVACY_FOLLOWING_SELECTED_ATTR}}>
                        {{PEOPLE_I_FOLLOW_LABEL}}
                    </option>
                </select>
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @comment_privacy_label@:
            </label>

            <div class="input floatLeft">
                <select name="comment_privacy">
                    <option value="everyone" {{COMMENT_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @everyone@
                    </option>

                    <option value="following" {{COMMENT_PRIVACY_FOLLOWING_SELECTED_ATTR}}>
                        {{PEOPLE_I_FOLLOW_LABEL}}
                    </option>
                </select>
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @timeline_post_privacy_label@:
            </label>

            <div class="input floatLeft">
                <select name="timeline_post_privacy">
                    <option value="everyone" {{TIMELINE_POST_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @everyone@
                    </option>

                    <option value="following" {{TIMELINE_POST_PRIVACY_FOLLOWING_SELECTED_ATTR}}>
                        {{PEOPLE_I_FOLLOW_LABEL}}
                    </option>

                    <option value="none" {{TIMELINE_POST_PRIVACY_NONE_SELECTED_ATTR}}>
                        @no_one@
                    </option>
                </select>
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="floatLeft">
                @post_privacy@:
            </label>

            <div class="input floatLeft">
                <select name="post_privacy">
                    <option value="everyone" {{POST_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @everyone@
                    </option>
                    
                    <option value="following" {{POST_PRIVACY_FOLLOWING_SELECTED_ATTR}}>
                        {{PEOPLE_I_FOLLOW_LABEL}}
                    </option>
                </select>
            </div>

            <div class="floatClear"></div>
        </div>

        <div class="form-input-wrapper">
            <button class="active">
                <i id="updatePrivacySettingsIcon" class="fa fa-lightbulb progress-icon hide"></i> 
                @save_changes_button@
            </button>
        </div>
    </div>
</form>

<script>
var birthdayVisibility = "{{USER_BIRTHDAY_VISIBILITY}}";

$('select[name="birthday_visibility"]').find('option[value="' + birthdayVisibility + '"]').attr("selected", "yes");

$('form.update-timeline-form').ajaxForm({
    url: Sk_requestPath()+'?t=user&a=settings',
    
    beforeSend: function()
    {
        iconProgress($("#updatePrivacySettingsIcon"));
    },
    
    success: function (responseText)
    {
        if (responseText.status === 200) location.reload();
        iconProgress($("#updatePrivacySettingsIcon"));
    }
});
</script>