<div class="page-margin"></div>

{{PAGE_NAVIGATION}}

<div class="floatLeft span52">
    <div class="e-album-photos-container">
        <div class="album-data">
            <div class="multiTabJar">
                <div class="boldTab">{{ALBUM_NAME}}</div>
                <div class="albumDescription">{{ALBUM_DESCR}}</div>
            </div>

            <div class="controlBtnContainer">
                {{UPLOAD_BUTTON}}
                {{EDIT_BUTTON}}
                {{DELETE_BUTTON}}
            </div>
        </div>

        {{EDIT_HTML}}

        <div class="album-photos">
            {{LIST_PHOTOS}}

            <div class="floatClear"></div>
        </div>
    </div>
</div>

<div class="floatRight span30">
    {{FEATURED_USERS}}

    {{USER_SUGGESTIONS}}

    {{PAGE_SUGGESTIONS}}

    {{GROUP_SUGGESTIONS}}
    
    {{TRENDINGS}}
    
    {{CONFIG_AD_PLACE_TIMELINE}}
</div>

<div class="floatClear"></div>

{{UPLOAD_FORM}}

<script>
    $(function () {
        $('form.e-album-form').ajaxForm({
            url: Sk_requestPath() + '?t=album&a=upload',
            
            beforeSend: function() {
                iconProgress($(".uploadIcon"));
            },

            uploadProgress: function(event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                var container = $('.e-album-uploader');
                container.find('span').text('@uploading@... ' + percentVal);

                if (percentComplete == 100) {
                    container.find('span').text('@please_wait@...');
                }
            },
            
            success: function(responseText) {
                var container = $('.e-album-uploader');

                if (responseText.status == 200) {
                    $('.album-photos').prepend(responseText.html);
                }

                iconProgress($(".uploadIcon"));
                container.find('span').text('Upload Photos');
            }
        });
    });

    function SK_deleteAlbumWindow(album_id) {
        button_wrapper = $('.album-delete-btn');
        iconProgress($(".deleteIcon"));

        $.get(Sk_requestPath(), {t: 'album', album_id: album_id, a: 'delete_window'}, function(data) {
            
            if (data.status == 200) {
                $(document.body)
                    .append(data.html)
                    .css('overflow','hidden');
                
                if ($('#mainHeaderJar').width() < 920) {
                    $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
                }
            }
            
            iconProgress($(".deleteIcon"));
        });
    }

    function SK_deleteAlbum(album_id) {
        SK_closeWindow();
        $.get(Sk_requestPath(), {t: 'album', album_id: album_id, a: 'delete'}, function(data) {
            
            if (data.status == 200) {
                window.location = data.location;
            }
        });
    }

    function editAlbum()
    {
        viewWrapper = $(".album-data");
        editWrapper = $(".album-edit-data");

        viewWrapper.hide();
        editWrapper.show();
    }

    function saveAlbumChanges()
    {
        albumName = $("input.album_name").val();
        albumDescr = $("textarea.album_descr").val();
        albumId = $("input.album_id").val();

        viewWrapper = $(".album-data");
        editWrapper = $(".album-edit-data");

        $.post(
            Sk_requestPath() + "?t=album&a=update_info",
            {
                album_id: albumId,
                album_name: albumName,
                album_descr: albumDescr
            },
            function(data)
            {
                if (data.status === 200)
                {
                    location.reload();
                }

                editWrapper.hide();
                viewWrapper.show();
            }
        );
    }

    function SK_viewRemove(post_id) {
        main_wrapper = $('.photo_ ' + post_id);
        button_wrapper = main_wrapper.find('.remove-btn');
        SK_progressIconLoader(button_wrapper);
        
        $.get(
            Sk_requestPath(),

            {
                t: 'post',
                post_id: post_id,
                a: 'view_remove'
            },

            function(data) {
                if (data.status == 200) {
                    $(document.body)
                        .append(data.html)
                        .css('overflow','hidden');
                    
                    if ($('#mainHeaderJar').width() < 920) {
                        $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
                    }
                }
                
                SK_progressIconLoader(button_wrapper);
            }
        );
    }

    // Cancel remove
    function SK_cancelRemove(post_id) {
        main_wrapper = $('.story_' + post_id);
        SK_progressIconLoader(main_wrapper.find('.remove-btn'));
        SK_closeWindow();
    }

    // Delete post
    function SK_removePost(post_id)
    {
        SK_closeWindow();

        $.get(
            Sk_requestPath(),

            {
                t: 'post',
                post_id: post_id,
                a: 'remove'
            },

            function(data)
            {
                if (data.status == 200)
                {
                    $('.story_' + post_id).slideUp(function(){
                        $(this).remove();
                    });

                    $('.photo_' + post_id).fadeOut(function(){
                        $(this).remove();
                    });
                }
            }
        );
    }
</script>