<div class="window-container">
    <div class="window-background" onclick="SK_closeWindow();"></div>

    <div class="window-wrapper">
        <div class="window-header-wrapper">
            <i class="fa fa-minus-sign"></i> 

            @delete_event_label@?

            <span class="window-close-btn" title="Close window" onclick="SK_cancelRemove({{TIMELINE_ID}});">
                <i class="fa fa-remove"></i>
            </span>
        </div>

        <div class="button-content-wrapper">
            <button onclick="SK_closeWindow();">
                @cancel@
            </button> 

            <button class="active" onclick="deleteEvent({{TIMELINE_ID}});">
                @delete_button@
            </button>
        </div>
    </div>
</div>