<div class="listJar">
    <div class="multiTabJar">
        <div class="floatLeft">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-calendar"></i> @events_label@
            </div>
        </div>

        <div class="floatRight">
            <a class="miniBoldTab" href="{{NEW_EVENT}}">
                <i class="fa fa-plus-circle"></i>
            </a>
        </div>

        <div class="floatClear"></div>
    </div>

    <div class="barDataList">
        {{LIST_EVENTS}}
    </div>
</div>