<div class="timeline-header-wrapper">
    <div class="cover-container">
        <div class="cover-wrapper">
            <img src="{{TIMELINE_COVER_URL}}" alt="@">
            <div class="cover-progress"></div>
        </div>
        
        <div class="cover-resize-wrapper">
            <img src="{{TIMELINE_ACTUAL_COVER_URL}}" alt="{{TIMELINE_NAME}}">
            <div class="drag-div" align="center">@reposition_drag_label@</div>
            <div class="cover-progress"></div>
        </div>
        
        <div class="avatar-wrapper">
            <img class="avatar" src="{{TIMELINE_AVATAR_URL}}" alt="{{TIMELINE_NAME}}">
            
            {{CHANGE_AVATAR_HTML}}
        </div>
        
        <div class="timeline-name-wrapper">
            <a href="{{TIMELINE_URL}}" data-href="?a=timeline&id={{TIMELINE_USERNAME}}">
                {{TIMELINE_NAME}}
            </a>
            
            {{VERIFIED_BADGE}}
        </div>
    </div>

    <div class="timeline-statistics-wrapper">
        <table border="0" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            {{FOLLOW_REQUESTS_LINK}}
            
            {{STORIES_LINK}}
            
            {{FOLLOWING_LINK}}

            <td class="statistic" align="center" valign="middle">
                <a>{{LIKES_NUM}} @people_likes_this_label@</a>
            </td>

            <td class="statistic" align="center" valign="middle">
                <a href="{{POSTS_TAB_URL}}" data-href="?a=timeline&b=stories&id={{TIMELINE_USERNAME}}">
                    {{POSTS_NUM}} @posts_label@
                </a>
            </td>
        </tr>
        </table>
    </div>
</div>

{{SIDEBAR}}

<div class="floatRight span63">
    {{STORY_POSTBOX}}

    {{STORY_FILTERS}}

    {{STORIES}}
</div>

<div class="floatClear"></div>
{{END}}