<div class="story-react-wrapper">
	<span class="cursorPointer" onclick="set_reaction('like', {{STORY_ID}});" data-title="@post_like_button_label@">
		<i class="fa fa-thumbs-up"></i>
	</span>

	<span class="cursorPointer" onclick="set_reaction('love', {{STORY_ID}});" data-title="@reaction_love_label@">
		<i class="skemoji skemoji-heart"></i>
	</span>

	<span class="cursorPointer" onclick="set_reaction('haha', {{STORY_ID}});" data-title="@reaction_haha_label@">
		<i class="skemoji skemoji-laughing"></i>
	</span>

	<span class="cursorPointer" onclick="set_reaction('wow', {{STORY_ID}});" data-title="@reaction_wow_label@">
		<i class="skemoji skemoji-open-mouth"></i>
	</span>

	<span class="cursorPointer" onclick="set_reaction('sad', {{STORY_ID}});" data-title="@reaction_sad_label@">
		<i class="skemoji skemoji-cry"></i>
	</span>
	
	<span class="cursorPointer" onclick="set_reaction('angry', {{STORY_ID}});" data-title="@reaction_angry_label@">
		<i class="skemoji skemoji-rage"></i>
	</span>
</div>