<div class="window-container">
    <div class="window-background" onclick="SK_closeWindow();"></div>

    <div class="reaction-wrapper">
        <div class="reaction-header-wrapper">
            <div class="reaction-header-tab selected-tab" title="All" onclick="viewReactions('all', {{REACTION_STORY_ID}}, this);">
                All
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab blue-tab" title="Like" onclick="viewReactions('like', {{REACTION_STORY_ID}}, this);">
                <i class="fa fa-thumbs-up" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_LIKES_NUM}}
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab red-tab" title="Love" onclick="viewReactions('love', {{REACTION_STORY_ID}}, this);">
                <i class="skemoji skemoji-heart" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_LOVE_NUM}}
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab yellow-tab" title="Haha" onclick="viewReactions('haha', {{REACTION_STORY_ID}}, this);">
                <i class="skemoji skemoji-laughing" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_HAHA_NUM}}
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab yellow-tab" title="Wow" onclick="viewReactions('wow', {{REACTION_STORY_ID}}, this);">
                <i class="skemoji skemoji-open-mouth" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_WOW_NUM}}
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab yellow-tab" title="Sad" onclick="viewReactions('sad', {{REACTION_STORY_ID}}, this);">
                <i class="skemoji skemoji-cry" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_SAD_NUM}}
            </div>

            <abbr class="space1">&#183;</abbr>

            <div class="reaction-header-tab orange-tab" title="Angry" onclick="viewReactions('angry', {{REACTION_STORY_ID}}, this);">
                <i class="skemoji skemoji-rage" style="display:inline-block;vertical-align:top;margin-top:2px;"></i>
                {{STORY_REACTION_ANGRY_NUM}}
            </div>

            <span class="reaction-close-btn" title="Close window" onclick="SK_closeWindow();">
                <i class="fa fa-times"></i>
            </span>
        </div>

        <div class="reaction-content-wrapper">
            {{LIST_LIKES}}
        </div>
    </div>
</div>
<script>
function viewReactions(typ, storyId, elm)
{
    $('.reaction-header-tab').removeClass('selected-tab');
    $(elm).addClass('selected-tab');

    $('.reaction-content-wrapper').html('<div class="popupColumnJar">@loading@</div>');

    $.get(
        Sk_requestPath(),

        {
            t: 'post',
            a: 'view_reactions_list',
            reaction_type: typ,
            post_id: storyId
        },

        function(data)
        {
            if (data.status == 200)
            {
                $('.reaction-content-wrapper').html(data.html);
            }
        }
    );
}
</script>