<div class="userColumn group-member-{{GROUP_REQUEST_USER_ID}}" data-user-id="{{GROUP_REQUEST_USER_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{GROUP_REQUEST_USER_URL}}" data-href="?a=timeline&id={{GROUP_REQUEST_USER_USERNAME}}">
            <img class="borderRadius100" src="{{GROUP_REQUEST_USER_THUMBNAIL_URL}}" alt="{{GROUP_REQUEST_USER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{GROUP_REQUEST_USER_URL}}" data-href="?a=timeline&id={{GROUP_REQUEST_USER_USERNAME}}">{{GROUP_REQUEST_USER_NAME}}</a>
        </strong>

        <small>{{GROUP_REQUEST_USER_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{GROUP_REQUESTS_BTN}}
    </div>

    <div class="floatClear"></div>
</div>