<div class="page-margin"></div>

{{PAGE_NAVIGATION}}

<div class="floatLeft span52">
    <div class="listJar">
        <div class="multiTabJar">
            <div class="boldTab">
                <i class="ski ski-group"></i>
                @my_groups@
            </div>
        </div>

        {{MY_GROUPS}}
    </div>
</div>

<div class="floatRight span30">
    {{USER_SUGGESTIONS}}

    {{PAGE_SUGGESTIONS}}

    {{GROUP_SUGGESTIONS}}

    {{TRENDINGS}}
    
    {{CONFIG_AD_PLACE_HASHTAG}}

    {{SIDEBAR_FOOTER}}
</div>

<div class="floatClear"></div>