<div class="userColumn myGROUP_{{GROUP_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{GROUP_URL}}" data-href="?a=timeline&id={{GROUP_USERNAME}}">
            <img class="borderRadius100" src="{{GROUP_THUMBNAIL_URL}}" alt="{{GROUP_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{GROUP_URL}}" data-href="?a=timeline&id={{GROUP_USERNAME}}">{{GROUP_NAME}}</a>
        </strong>

        <small>{{GROUP_INFO}}</small>
    </div>

    <div class="floatClear"></div>
</div>