<div class="floatLeft span25">
    <div class="listJar">
        <a class="infoColumn" href="{{TIMELINE_URL}}" data-href="?a=timeline&id={{TIMELINE_USERNAME}}" align="center">
            {{TIMELINE_NAME}}
        </a>
    </div>
    
    <div class="listJar">
        <div class="multiTabJar">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-align-justify"></i>
                @menu_label@
            </div>
        </div>
        
        {{GENERAL_LINK}}
        
        {{PRIVACY_LINK}}
        
        {{ADMIN_ROLES_LINK}}
        
        {{MESSAGES_LINK}}
        
        {{LIKES_LINK}}
    </div>
</div>