<div id="msg-{{MSG_ID}}" class="chatTxt incomingMsg" name="msg-{{MSG_ID}}" data-msg-id="{{MSG_ID}}">
    <div class="imgJar floatLeft">
        <a href="{{MSG_USR_URL}}" data-href="?a=timeline&id={{MSG_USR_USERNAME}}">
            <img class="borderRadius100" src="{{MSG_USR_THUMB}}" alt="{{MSG_USR_NAME}}">
        </a>
    </div>

    <div class="txtCntnr floatLeft">
        {{MSG_TXT}}
        {{MSG_MEDIA}}
    </div>

    <div class="floatClear"></div>
</div>