<div class="userColumn suggestion_{{LIST_FOLLOWER_ID}}" data-user-id="{{LIST_FOLLOWER_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_FOLLOWER_URL}}" data-href="?a=timeline&id={{LIST_FOLLOWER_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_FOLLOWER_THUMBNAIL_URL}}" alt="{{LIST_FOLLOWER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_FOLLOWER_URL}}" data-href="?a=timeline&id={{LIST_FOLLOWER_USERNAME}}">{{LIST_FOLLOWER_NAME}}</a>
        </strong>

        <small>{{LIST_FOLLOWER_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_FOLLOWER_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>