<div class="userColumn follow-request-{{LIST_REQUEST_ID}}" data-user-id="{{LIST_REQUEST_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_REQUEST_URL}}" data-href="?a=timeline&id={{LIST_REQUEST_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_REQUEST_THUMBNAIL_URL}}" alt="{{LIST_REQUEST_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_REQUEST_URL}}" data-href="?a=timeline&id={{LIST_REQUEST_USERNAME}}">{{LIST_REQUEST_NAME}}</a>
        </strong>

        <small>{{LIST_REQUEST_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_REQUEST_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>