<div class="listJar">
    <div class="multiTabJar">
        <div class="boldTab">@group_add_members_label@</div>
    </div>
    
    {{ADD_MEMBER_USERLISTS}}
</div>

<script>
function SK_addGroupMember(group_id, member_id) {
    $('.follower-id-' + member_id).find('.addBtn').text('@adding@..');
    
    $.post(Sk_requestPath() + '?t=group&a=add_member', {group_id: group_id, member_id: member_id}, function (data) {
        
        if (data.status == 200) {
            $('.follower-id-' + member_id).slideUp(function() {
                $(this).remove();
            });
        }
    });
}
</script>