<div class="listJar">
    <div class="multiTabJar">
        <div class="boldTab">@group_admins_label@</div>
    </div>

    <div class="list-admins">
        {{LIST_ADMIN_USERLISTS}}
    </div>

    <a class="infoColumn view-more-anchor hide" align="center" onclick="listMembers();">
        @view_more@
    </a>
</div>

<script>
$(function(){
    if ($(".list-admins").find(".userColumn").length > 0)
    {
        $(".view-more-anchor").removeClass("hide");
    }
});

function listMembers() {
    lastFollowId = $(".list-admins").find(".userColumn:last").attr('data-user-id');
    $.get(
        Sk_requestPath(),
        {
            t: "user",
            a: "list_group_admins",
            timeline_id: {{TIMELINE_ID}},
            before_id: lastFollowId
        },
        function(data)
        {
            if (data.status == 200)
            {
                if (data.html.length > 0)
                {
                    $(".list-admins").append(data.html);
                }
                else
                {
                    $(".view-more-anchor").hide();
                }
            }
        }
    );
}

function SK_removeGroupAdmin(group_id, admin_id) {
    $('.group-admin-' + admin_id).find('.removeBtn').text('Removing..');
    
    $.post(Sk_requestPath() + '?t=group&a=remove_admin', {group_id: group_id, admin_id: admin_id}, function (data) {
        
        if (data.status == 200) {
            $('.group-admin-' + admin_id).slideUp(function () {
                $(this).remove();
            });
        }
    });
}
</script>