<form class="update-page-privacy" method="post">
    <div class="form-container">
        <div class="multiTabJar">
            <div class="boldTab">
                <i class="fa fa-lock"></i>
                @privacy_settings_label@
            </div>
        </div>
        <div class="form-input-wrapper">
            <label class="floatLeft span35">
                @pages_timeline_post_privacy@:
            </label>
            <div class="input floatLeft span55">
                <select name="timeline_post_privacy">
                    <option value="everyone" {{POST_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @yes@
                    </option>

                    <option value="none" {{POST_PRIVACY_NONE_SELECTED_ATTR}}>
                        @no@
                    </option>
                </select>
            </div>
            <div class="floatClear"></div>
        </div>
        <div class="form-input-wrapper">
            <label class="floatLeft span35">
                @pages_message_privacy@:
            </label>
            <div class="input floatLeft span55">
                <select name="message_privacy">
                    <option value="everyone" {{MESSAGE_PRIVACY_EVERYONE_SELECTED_ATTR}}>
                        @yes@
                    </option>
                    
                    <option value="none" {{MESSAGE_PRIVACY_NONE_SELECTED_ATTR}}>
                        @no@
                    </option>
                </select>
            </div>
            <div class="floatClear"></div>
        </div>
        <div class="form-input-wrapper">
            <button id="privacyBtn" class="active">
                <i class="fa fa-lightbulb progress-icon hide"></i> 
                @save_changes_button@
            </button>
        </div>
    </div>
    <input name="timeline_id" value="{{TIMELINE_ID}}" type="hidden">
</form>
<script>
$ (function () {
    $('form.update-page-privacy').ajaxForm({
        url: Sk_requestPath() + '?t=page&a=update',

        beforeSend: function(){
            $("#privacyBtn").attr("disabled", true);
        }
        
        success: function (responseText) {
            
            if (responseText.status == 200) {
                
                if ($('.success-message').length == 0) {
                    $('.form-header').after('<div class="success-message hidden">@changes_saved@.</div>');
                    $('.success-message').fadeIn('fast',function () {
                        $(this).fadeOut(1500, function() {
                            $(this).remove();
                        });
                    });
                }
            }
        }
    });
});
</script>