<div class="page-margin"></div>
<div class="floatLeft span20">
    <div class="listJar">
        <div class="multiTabJar">
            <div class="semiBoldTab lightColor">
                <i class="fa fa-align-justify"></i>
                @pages@
            </div>
        </div>
        
        <a class="infoColumn lightColor" href="{{TERMS_TOS_URL}}" data-href="?a=terms&b=tos">
            @terms_tos_label@
        </a>
        
        <a class="infoColumn lightColor" href="{{TERMS_PRIVACY_URL}}" data-href="?a=terms&b=privacy">
            @terms_privacy_label@
        </a>
        
        <a class="infoColumn lightColor" href="{{TERMS_DISCLAIMER_URL}}" data-href="?a=terms&b=disclaimer">
            @terms_disclaimer_label@
        </a>
        
        <a class="infoColumn lightColor" href="{{TERMS_CONTACT_URL}}" data-href="?a=terms&b=contact">
            @terms_contact_label@
        </a>
        
        <a class="infoColumn lightColor" href="{{TERMS_ABOUT_URL}}" data-href="?a=terms&b=about">
            @terms_about_label@
        </a>
        
        <a class="infoColumn lightColor" href="{{TERMS_DEVELOPERS_URL}}" data-href="?a=terms&b=developers">
            @terms_developers_label@
        </a>
    </div>
</div>

<div class="floatRight span79">
    {{TERMS_CONTENT}}
</div>

<div class="floatClear"></div>

{{BOTTOM_FOOTER}}