<script>
// Like story
function set_reaction(reaction, story_id)
{
    story_container = $(".story_" + story_id);
    like_button = story_container.find('.story-like-btn');
    like_activity_button = story_container.find('.story-like-activity');

    SK_progressIconLoader(like_button);
    SK_progressImageLoader(like_button.find('img.progress-img'));
    
    $.get(
        Sk_requestPath(),

        {
            t: 'post',
            a: 'like',
            reaction: reaction,
            post_id: story_id
        },

        function(data)
        {
            if (data.status == 200)
            {
                if (data.liked == true)
                {
                    like_button
                        .after(data.button_html)
                        .remove();

                    like_activity_button
                        .html(data.activity_html);
                } else {
                    like_button
                        .after(data.button_html)
                        .remove();

                    like_activity_button
                        .html(data.activity_html);
                }
            }
        }
    );
}

function getStoryReactions(post_id) {
    main_elem = $('.story_' + post_id);
    like_activity_btn = main_elem.find('.like-activity');
    SK_progressIconLoader(like_activity_btn);
    
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'view_likes'}, function(data) {
        
        if (data.status == 200) {
            $(document.body)
                .append(data.html)
                .css('overflow','hidden');
            
            if ($('#mainHeaderJar').width() < 920) {
                $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
            }
        }
        
        SK_progressIconLoader(like_activity_btn);
    });
}

function submitComment(event,pid)
{
    if (event.keyCode == 13 && event.shiftKey == 0)
    {
        event.preventDefault();
        postComment(pid);
    }
}

function postComment(pid)
{
    $('.story_' + pid).find('form.comment-textarea').ajaxSubmit({
        url: Sk_requestPath() + '?t=post&a=comment&post_id=' + pid,
        
        beforeSend: function() {
            postWrap = $('.story_' + pid);
            textareaWrap = postWrap.find('.comment-textarea');
            textarea = textareaWrap.find('textarea');
            uploadIcon = textareaWrap.find('i.img-upload-icon');
            previewWrap = textareaWrap.find('div.photo-preview');
            previewImg = previewWrap.find('img');
            textarea.val('');

            uploadIcon.hide();

            SK_progressIconLoader(textareaWrap);
        },
        
        uploadProgress: function(event, position, total, percentComplete) {},
        
        success: function(responseText) {
            if (responseText.status == 200) {
                postWrap.find('.commentJar:last').before(responseText.html);
                postWrap.find('.story-comment-activity').html(responseText.activity_html);
            }

            SK_progressIconLoader(textareaWrap);
            previewWrap.hide();
            previewImg.attr('src', '');
            uploadIcon.show();
        }
    });
}

// Share story
function SK_registerStoryShare(post_id) {
    main_elem = $('.story_'+post_id);
    share_btn = main_elem.find('.story-share-btn');
    share_activity_btn = main_elem.find('.story-share-activity');
    
    SK_progressIconLoader(share_btn);
    
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'share'}, function(data) {
        if (data.status == 200) {
            if (data.shared == true) {
                share_btn
                    .after(data.button_html)
                    .remove();
                share_activity_btn
                    .html(data.activity_html);
            } else {
                share_btn
                    .after(data.button_html)
                    .remove();
                share_activity_btn
                    .html(data.activity_html);
            }
        }
    });
}

// Follow story
function SK_registerStoryFollow(post_id) {
    main_elem = $('.story_'+post_id);
    follow_btn = main_elem.find('.story-follow-btn');
    follow_activity_btn = main_elem.find('.story-follow-activity');
    
    SK_progressIconLoader(follow_btn);
    
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'follow'}, function(data) {
        if (data.status == 200) {
            if (data.shared == true) {
                follow_btn
                    .after(data.button_html)
                    .remove();
                follow_activity_btn
                    .html(data.activity_html);
            } else {
                follow_btn
                    .after(data.button_html)
                    .remove();
                follow_activity_btn
                    .html(data.activity_html);
            }
        }
    });
}

// Show post likes window (popup)
function SK_getStoryLikes(post_id) {
    main_elem = $('.story_' + post_id);
    like_activity_btn = main_elem.find('.like-activity');
    SK_progressIconLoader(like_activity_btn);
    
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'view_likes'}, function(data) {
        
        if (data.status == 200) {
            $(document.body)
                .append(data.html)
                .css('overflow','hidden');
            
            if ($('#mainHeaderJar').width() < 920) {
                $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
            }
        }
        
        SK_progressIconLoader(like_activity_btn);
    });
}

// Show post shares window
function SK_getStoryShares(post_id) {
    main_elem = $('.story_' + post_id);
    share_activity_btn = main_elem.find('.share-activity');
    SK_progressIconLoader(share_activity_btn);
    
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'view_shares'}, function(data) {
        
        if (data.status == 200) {
            $(document.body)
                .append(data.html)
                .css('overflow','hidden');
            
            if ($('#mainHeaderJar').width() < 920) {
                $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
            }
        }
        
        SK_progressIconLoader(share_activity_btn);
    });
}

// Show delete post window
function SK_viewRemove(post_id) {
    main_wrapper = $('.story_' + post_id);
    button_wrapper = main_wrapper.find('.remove-btn');
    SK_progressIconLoader(button_wrapper);
    
    $.get(
        Sk_requestPath(),

        {
            t: 'post',
            post_id: post_id,
            a: 'view_remove'
        },

        function(data) {
            if (data.status == 200) {
                $(document.body)
                    .append(data.html)
                    .css('overflow','hidden');
                
                if ($('#mainHeaderJar').width() < 920) {
                    $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
                }
            }
            
            SK_progressIconLoader(button_wrapper);
        }
    );
}

// Cancel remove
function SK_cancelRemove(post_id) {
    main_wrapper = $('.story_' + post_id);
    SK_progressIconLoader(main_wrapper.find('.remove-btn'));
    SK_closeWindow();
}

// Delete post
function SK_removePost(post_id) {
    SK_closeWindow();
    $.get(Sk_requestPath(), {t: 'post', post_id: post_id, a: 'remove'}, function(data) {
        
        if (data.status == 200) {
            $('.story_' + post_id).slideUp(function(){
                $(this).remove();
            });

            $('.photo_' + post_id).fadeOut(function(){
                $(this).remove();
            });
        }
    });
}

// Report Post
function SK_reportPost(post_id)
{
    main_wrapper = $('.story_' + post_id);
    SK_progressIconLoader(main_wrapper.find('.report-btn'));
    
    $.get (Sk_requestPath(), {t: 'post', post_id: post_id, a: 'report'}, function(data) {
        
        if (data.status == 200) {
            
            main_wrapper.find('.report-btn').text('Reported!').fadeOut(1500);
        }
        
        SK_progressIconLoader($('.story_' + post_id).find('.report-btn'));
    });
}

// Load old stories
function SK_loadOldStories() {
    body_wrapper = $('.stories-container');
    button_wrapper = $('.stories-container').find('.load-btn');
    
    SK_progressIconLoader(button_wrapper);
    
    outgoing_data = new Object();
    outgoing_data.t = 'post';
    outgoing_data.a = 'filter';
    
    if ( typeof(body_wrapper.attr('data-story-type')) == "string" ) {
        outgoing_data.type = body_wrapper.attr('data-story-type');
    }
    
    if ( typeof(body_wrapper.attr('data-story-timeline')) =="string" ) {
        outgoing_data.timeline_id = body_wrapper.attr('data-story-timeline');
    }
    
    if ($('.singleStoryJar').length > 0) {
        outgoing_data.after_id = $('.singleStoryJar:last').attr('data-story-id');
    }
    
    $.get(Sk_requestPath(), outgoing_data, function (data) {
        
        if (data.status == 200 ) {
            $('.stories-wrapper').append(data.html);
        } else {
            button_wrapper.text('No more posts to show').removeAttr('onclick');
        }
        
        SK_progressIconLoader(button_wrapper);
        
    });
}

/* Like comment */
function likeComment(comment_id) {
    main_elem = $('.comment_' + comment_id);
    like_btn = main_elem.find('.comment-like-btn');
    like_activity_btn = main_elem.find('.comment-like-activity');
    
    SK_progressIconLoader(like_btn);
    
    $.get(
        Sk_requestPath(),

        {
            t: 'comment',
            comment_id: comment_id,
            a: 'like'
        },

        function(data) {
            if (data.status == 200)
            {
                if (data.liked == true)
                {
                    like_btn
                        .after(data.button_html)
                        .remove();
                    like_activity_btn
                        .html(data.activity_html);
                }
                else
                {
                    like_btn
                        .after(data.button_html)
                        .remove();
                    like_activity_btn
                        .html(data.activity_html);
                }
            }
        }
    );
}

/* View comment likes */
function viewCommentLikes(comment_id) {
    main_elem = $('.comment_' + comment_id);
    like_activity_btn = main_elem.find('.comment-like-activity');
    SK_progressIconLoader(like_activity_btn);
    
    $.get(
        Sk_requestPath(),

        {
            t: 'comment',
            comment_id: comment_id,
            a: 'view_likes'
        },

        function(data) {
            if (data.status == 200)
            {
                $(document.body)
                    .append(data.html)
                    .css('overflow','hidden');
                
                if ($('#mainHeaderJar').width() < 920)
                {
                    $('.window-wrapper').css('margin-top', ($(document).scrollTop() + 10) + 'px');
                }
            }
            
            SK_progressIconLoader(like_activity_btn);
        }
    );
}

/* Report Comment */
function reportComment(comment_id)
{
    main_wrapper = $('.comment_' + comment_id);
    SK_progressIconLoader(main_wrapper.find('.report-btn'));
    
    $.get (
        Sk_requestPath(),

        {
            t: 'comment',
            comment_id: comment_id,
            a: 'report'
        },

        function(data)
        {
            if (data.status == 200)
            {
                main_wrapper.find('.report-btn').text('Reported!').fadeOut(1500);
            }
            SK_progressIconLoader($('.comment_' + comment_id).find('.report-btn'));
        }
    );
}

/* View comment remove */
function viewCommentRemove(comment_id) {
    main_wrapper = $('.comment_' + comment_id);
    button_wrapper = main_wrapper.find('.comment-remove-btn');
    
    SK_progressIconLoader(button_wrapper);
    
    $.get(
        Sk_requestPath(),

        {
            t: 'comment',
            comment_id: comment_id,
            a: 'view_remove'
        },

        function(data)
        {
            if (data.status == 200)
            {
                $(document.body)
                    .append(data.html)
                    .css('overflow','hidden');
                
                if ($('#mainHeaderJar').width() < 920)
                {
                    $('.window-wrapper').css('margin-top', ($(document).scrollTop()+10)+'px');
                }
            }
            
            SK_progressIconLoader(button_wrapper);
        }
    );
}

/* Cancel comment remove */
function cancelCommentRemove(comment_id) {
    button = $('.comment_' + comment_id).find('.remove-btn');
    SK_progressIconLoader(button);
    SK_closeWindow();
}

/* Remove comment */
function removeComment(comment_id) {
    SK_closeWindow();

    $.get(
        Sk_requestPath(),

        {
            t: 'comment',
            comment_id: comment_id,
            a: 'remove'
        },

        function(data)
        {
            if (data.status == 200)
            {
                $('.comment_' + comment_id).slideUp(function() {
                    $(this).remove();
                });
            }
        }
    );
}

/* View all comments */
function viewAllComments(post_id) {
    main_wrapper = $('.story_' + post_id);
    view_more_wrapper = main_wrapper.find('.viewMoreJar');
    
    SK_progressIconLoader(view_more_wrapper);
    
    $.get(Sk_requestPath(), {t: 'post', a: 'view_all_comments', post_id: post_id}, function (data) {
        
        if (data.status == 200) {
            main_wrapper.find('.comments-wrapper').html(data.html);
            view_more_wrapper.remove();
        }
    });
}
</script>