<div id="message-{{MESSAGE_ID}}" class="messageJar incomingMessage" data-message-id="{{MESSAGE_ID}}">
    <div class="imageJar floatLeft">
        <a href="{{MESSAGE_TIMELINE_URL}}" data-href="?a=timeline&id={{MESSAGE_TIMELINE_USERNAME}}">
            <img class="borderRadius100" src="{{MESSAGE_TIMELINE_THUMBNAIL_URL}}" alt="{{MESSAGE_TIMELINE_NAME}}">
        </a>
    </div>

    <div class="textContainer floatLeft">
        {{MESSAGE_TEXT}}
        {{MESSAGE_MEDIA}}
    </div>

    <div class="floatClear"></div>
</div>