<form id="resetForm" method="post">
    <div class="formInfo"></div>

    <div id="resetUsernameInput" class="welcomeInput">
        <i class="fa fa-unlock"></i>
        <input id="resetPassword" type="password" name="pr_password" placeholder="@new_password_label@" autocomplete="off" required>
        <a class="endInfo resetPasswordToggleShow"><i class="fa fa-eye"></i></a>
    </div>

    <button id="resetBtn"><i id="resetBtnIcon" class="fa fa-unlock-alt" data-icon="unlock-alt"></i> @reset_password_label@</button>
    <input type="hidden" name="pr_token" value="{{GET_ID}}">
</form>
<script>
$(".resetPasswordToggleShow").click(function(e){
	e.stopPropagation();
	$("#resetPassword").attr("type", ($("#resetPassword").attr("type") === "password") ? "text" : "password");
});
$("#resetBtn").click(function(event){
  event.preventDefault();
  if ($("#resetPassword").val() === "")
  {
    $("#resetForm .formInfo").hide().removeClass("success").addClass("error").html('<i class="fa fa-info-circle"></i> @type_new_password@').fadeIn('fast');
  }
  else
  {
    $("#resetForm").ajaxSubmit({
      url: Sk_requestPath() + "?t=reset_password",
      
      beforeSend: function()
      {
        iconProgress($("#resetBtnIcon"));
        $("#resetForm input, #resetForm button").attr("disabled", true);
      },
          
      success: function(responseText)
      {
        if (responseText.status === 200)
        {
            $("#resetForm .formInfo").hide().removeClass("error").addClass("success").html('<i class="fa fa-check-circle"></i> @password_change_successfully@').fadeIn('fast');
            $("#resetBtn").addClass("success").html('<i class="fa fa-check-circle"></i> @reset_successful@').attr("disabled", false);
            setTimeout(function(){
                window.location = responseText.url;
            }, 750);
        }
      }
    });
  }
});
</script>