<div class="timeline-buttons cover-resize-buttons">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="middle">
            <a onclick="SK_saveReposition();">
                <i class="fa fa-check"></i>
                @save_position_label@
            </a>
        </td>

        <td align="center" valign="middle">
            <a onclick="SK_cancelReposition();">
                <i class="fa fa-times"></i>
                @cancel@
            </a>
        </td>
    </tr>
    </table>
    <form class="cover-position-form hidden" method="post">
        <input class="cover-position" name="pos" value="0" type="hidden">
        <input class="screen-width" name="width" value="920" type="hidden">
        <input name="timeline_id" value="{{TIMELINE_ID}}" type="hidden">
    </form>
</div>

<div class="timeline-buttons default-buttons">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="middle">
            <a onclick="javascript:$('.change-avatar-input').click();">
                <i class="fa fa-camera"></i>
                @change_avatar_label@
            </a>
        </td>
        
        <td align="center" valign="middle">
            <a href="{{SETTINGS_TAB_URL}}" data-href="?a=settings">
                <i class="fa fa-pencil-square"></i> 
                @edit_profile_label@
            </a>
        </td>
    </tr>
    
    <tr>
        <td align="center" valign="middle">
            <a onclick="javascript:$('.cover-image-input').click();">
                <i class="fa fa-image"></i> 
                @change_cover_label@
            </a>
        </td>
        
        <td align="center" valign="middle">
            <a onclick="SK_repositionCover();">
                <i class="fa fa-arrows"></i> 
                @reposition_cover_label@
            </a>
        </td>
    </tr>
    </table>
</div>

<form class="cover-form hidden" method="post" enctype="multipart/form-data" action="{{CONFIG_REQUEST_SOURCE}}?t=cover&a=post_upload">
    <input class="cover-image-input hidden" type="file" name="image" accept="image/jpeg,image/png" onchange="javascript:$('form.cover-form').submit();">
    <input name="timeline_id" value="{{TIMELINE_ID}}" type="hidden">
</form>