<script src="{{CONFIG_THEME_URL}}/javascript/lettering.js"></script>
<script src="{{CONFIG_THEME_URL}}/javascript/datepicker.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
<link href="{{CONFIG_THEME_URL}}/css/animate.css" rel="stylesheet">
<link href="{{CONFIG_THEME_URL}}/css/datepicker.css" rel="stylesheet">
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.switchInput {
	text-align: left;
	margin-bottom: 15px;
}

label {
    position: relative;
    display: inline-block;
    vertical-align: middle;
}
.switch {
    width: 50px;
    height: 24px;
}

.switch input {
	display:none;
}

.slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #e2e3e6;
    -webkit-transition: .4s;
    transition: .4s;
    border-radius: 34px;
}

.slider:before {
    position: absolute;
    content: "";
    height: 16px;
    width: 16px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
    border-radius: 50%;
}

input:checked + .slider {
    background-color: #5687a5;
}

input:focus + .slider {
    box-shadow: 0 0 1px #5687a5;
}

input:checked + .slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
}

.keepLogged {
    color: #777c8a;
}

#regGenderInput {
    padding: 0;
    width: 75%;
}
#regGenderInput label:first-of-type {
    float: left;
}
#regGenderInput label:last-of-type {
    float: right;
}
#regGenderInput label {
    display: block;
    width: 50%;
    background: inherit;
    text-align: center;
}
#regGenderInput label input[type="radio"] {
    display: none;
}
#regGenderInput label .title {
    background: inherit;
    padding: 10px 0;
    border-radius: 2px;
    transition: all 200ms ease-in-out;
    cursor: pointer;
}
#regGenderInput label.female input[type="radio"]:checked + .title {
    background: #da77a4;
    color: white;
}
#regGenderInput label.male input[type="radio"]:checked + .title {
    background: #5daff7;
    color: white;
}

#socialLogins {
    margin-top: 15px;
}
#socialLogins a {
    display: inline-block;
    padding: 10px 10px 0;
    font-size: 35px;
    transition: color 150ms ease-in-out;
}
#socialLogins a.facebook:hover {
    color: #3b5998;
}
#socialLogins a.twitter:hover {
    color: #1da1f2;
}
#socialLogins a.google:hover {
    color: #db4437;
}
#socialLogins a.instagram:hover {
    color: #003569;
}

.userProfiles {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 100%;
    z-index: 3;
}
.userProfile {
    position: absolute;
    display: none;
}
.userProfiles .closeLeft {
    left: 4.678546875%;
}
.userProfiles .closeRight {
    right: 4.678546875%;
}
.userProfiles .farLeft {
    left: 23.2218229167%;
}
.userProfiles .farRight {
    right: 23.2218229167%;
}
.userProfile.first {
    top: 4%;
}
.userProfile.second {
    top: 21%;
}
.userProfile.third {
    top: 38%;
}
.userProfile.fourth {
    top: 55%;
}
.userProfile.fifth {
    top: 72%;
}

.userProfile .msgWrap {
    display: none;
    position: absolute;
    color: white;
    top: 50%;
    transform: translateY(-50%);
    background: #85b6e0;
    padding: 10px;
    border-radius: 4px;
}
.userProfile .msgWrap.left {
    left: 125%;
}
.userProfile .msgWrap.right {
    right: 125%;
}
.userProfile .msgWrap:before {
    content: "";
    position: absolute;
    width: 10px;
    height: 10px;
    background: inherit;
    top: 45%;
}
.userProfile .msgWrap.left:before {
    left: -1px;
    transform: rotate(45deg) translate(-50%);
}
.userProfile .msgWrap.right:before {
    right: -8px;
    transform: rotate(45deg) translate(-50%);
}
.userProfile .msgWrap .msg {
    max-width: 260px;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
    font-size: 13px;
}
.userProfile img {
    background: url('{{CONFIG_USER_DEFAULT_MALE_AVATAR}}');
    width: 56px;
    height: 56px;
    border-radius: 100%;
}

[data-tooltip] {
  position: relative;
  z-index: 2;
  cursor: pointer;
}
[data-tooltip]:before,
[data-tooltip]:after {
  visibility: hidden;
  opacity: 0;
  pointer-events: none;
}
[data-tooltip]:before {
  position: absolute;
  bottom: 150%;
  left: 50%;
  margin-bottom: 5px;
  margin-left: -80px;
  padding: 7px;
  width: 100px;
  border-radius: 3px;
  background-color: #000;
  background-color: hsla(0, 0%, 20%, 0.9);
  color: #fff;
  content: attr(data-tooltip);
  text-align: center;
  font-size: 12px;
  line-height: 1.2;
}
[data-tooltip]:after {
  position: absolute;
  bottom: 150%;
  left: 50%;
  margin-left: -5px;
  width: 0;
  border-top: 5px solid #000;
  border-top: 5px solid hsla(0, 0%, 20%, 0.9);
  border-right: 5px solid transparent;
  border-left: 5px solid transparent;
  content: " ";
  font-size: 0;
  line-height: 0;
}
[data-tooltip]:hover:before,
[data-tooltip]:hover:after {
  visibility: visible;
  opacity: 1;
}

@media only screen and (max-device-width:960px),
only screen and (max-width:960px) {
    .welcomeForm {
        min-width: 0 !important;
    }
}

body {
  background: black;
}

#pageContainer {
  margin: 0;
  max-width: auto;
}
.welcomeBackground {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
}
.welcomeBgImage {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: url('{{CONFIG_THEME_URL}}/images/grid.png');
    background-repeat: repeat;
    opacity: 0.1;
}
.welcomeBackground video#bgVideo { 
    position: fixed;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 100%;
    width: auto;
    height: auto;
    z-index: -1;
    transform: translateX(-50%) translateY(-50%);
    background-repeat: no-repeat;
    background-size: cover;
}
.welcomeBackground #bgImage {
    position: fixed;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 100%;
    width: auto;
    height: auto;
    z-index: -2;
    transform: translateX(-50%) translateY(-50%);
    background-repeat: no-repeat;
    background-size: cover;
}
#bgImage {
  display: none;
}

.welcomeFormContainer {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
    z-index: 4;
    text-align: center;
}
.welcomeKitLogo {
    margin-bottom: 10px;
}
.welcomeKitLogo img {
  max-width: 100%;
}
.welcomeForm {
  position: relative;
  background: white;
  min-width: 300px;
  max-width: 300px;
  margin: 0 auto;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.welcomeForm form:not(:first-of-type) {
  display: none;
}
.welcomeForm .formInfo {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
  text-align: left;
  transition: background 200ms ease-in-out;
  border-radius: 2px;
}
.welcomeForm .formInfo:empty {
  display: none;
}
.welcomeForm .formInfo.error {
  background: #eac3c7;
}
.welcomeForm .formInfo.success {
  background: #b8ecb8;
}
.welcomeForm .welcomeInput {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  color: #a3a7b1;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 0 15px;
  box-sizing: border-box;
  font-size: 14px;
  text-align: left;
  transition: background 200ms ease-in-out;
  border-radius: 2px;
  position: relative;
}
.welcomeForm .welcomeInput i {
    display: inline-block;
    width: 16px;
    color: inherit;
    text-align: center;
}
.welcomeForm .welcomeInput.focused {
    background: #5687a5 !important;
    color: white;
}
.welcomeForm .welcomeInput input,
.welcomeForm .welcomeInput textarea {
    display: inline-block;
    background: inherit;
    color: inherit;
    border: 0;
    margin: 0 0 0 5px;
    width: 86%;
    padding: 15px 0;
}
.welcomeForm .welcomeInput textarea {
  width: 96%;
  padding: 15px 0 5px;
}
.welcomeForm .welcomeInput .endInfo {
  font-size: 15px;
  position: absolute;
  right: 5px;
  top: 50%;
  transform: translateY(-50%);
  transition: all 250ms ease-in-out;
  opacity: 1;
  visibility: visible;
}
.welcomeForm .welcomeInput .endInfo.check {
  color: #61c160;
}
.welcomeForm .welcomeInput.focused .endInfo {
  opacity: 0;
  visibility: hidden;
}
.welcomeForm .welcomeCaptcha {
  font-family: "Roboto", sans-serif;
  outline: 0;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  box-sizing: border-box;
  text-align: left;
}
.welcomeForm button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #5687a5;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.welcomeForm button.success {
  background: #61c160 !important;
}
.welcomeForm button:disabled {
  background: rgb(223, 223, 223) !important;
  color: rgb(159, 159, 159);
  cursor: auto;
}
.welcomeForm button i {
  display: inline-block;
  margin-right: 3px;
}
.welcomeForm .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.welcomeForm .message a {
  color: #5687a5;
  text-decoration: none;
}

.welcomeHeadings {
  color: white;
  text-shadow: 1px 1px 6px rgba(0, 0, 0, .85);
  font-size: 25px;
  font-weight: normal;
  margin-top: 30px;
}

.welcomeFooter {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 5;
  padding: 20px;
  font-size: 16px;
  text-align: center;
  text-shadow: 1px 1px 5px rgba(0, 0, 0, .8);
}
.welcomeFooter, .welcomeFooter a {
  color: white;
}
.welcomeFooter .footerLink {
  display: inline-block;
  position: relative;
  cursor: pointer;
}
.welcomeFooter .footerLink .dropup {
  position: absolute;
  width: 95px;
  bottom: 140%;
  padding: 4px 0;
  background: white;
  border-top: 1px solid rgba(0, 0, 0, .1);
  border-radius: 4px;
  box-shadow: 0 6px 12px rgba(0,0,0,.175);
  -webkit-transition: opacity 250ms ease-in-out;
  -moz-transition: opacity 250ms ease-in-out;
  -o-transition: opacity 250ms ease-in-out;
  transition: opacity 250ms ease-in-out;
  display: none;
}
.welcomeFooter .footerLink .dropupLeft {
  left: 0;
}
.welcomeFooter .footerLink .dropupRight {
  right: 0;
}
.welcomeFooter .footerLink .dropup a {
  display: block;
  color: #4e5665;
  font-size: 12px;
  padding: 7px 8px;
  text-shadow: 0 0 0 transparent;
}
.welcomeFooter .footerLink .dropup a:hover {
  background: #f6f6f6;
  color: #4a4f58;
  text-decoration: none;
}
.welcomeFooter .separator {
  margin: 0 5px;
  font-size: 3px;
  display: inline-block;
  vertical-align: middle;
}

input::-webkit-input-placeholder,
textarea::-webkit-input-placeholder {
    color: inherit;
}
input:-moz-placeholder,
textarea:-moz-placeholder {
    color: inherit;
    opacity: 1;
}
input::-moz-placeholder,
textarea::-moz-placeholder {
    color: inherit;
    opacity: 1;
}
input:-ms-input-placeholder,
textarea:-ms-input-placeholder {
    color: inherit;
}

@media only screen and (max-device-width:960px),
only screen and (max-width:960px) {
  body {
    margin: 0 8px;
  }
  #bgVideo {
    display: none;
  }
  #bgImage {
    display: block;
  }
  .welcomeFormContainer, .welcomeFooter {
    position: relative;
    top: auto;
    left: auto;
    bottom: auto;
    right: auto;
    padding: 0;
    transform: translateX(0%) translateY(0%);
  }
  .welcomeFormContainer {
    margin-top: 15px;
  }
  .welcomeFooter {
    margin: 20px 0;
    font-size: 12px;
  }
  .welcomeFooter .floatRight {
    margin-top: 8px;
  }
  .welcomeKitLogo img {
    max-width: 75%;
  }
  .welcomeHeadings {
    font-size: 20px;
    margin: 20px 0;
  }
}
</style>
<script src="{{CONFIG_THEME_URL}}/javascript/textillate.js"></script>