<a href="{{ABOUT_PAGE_URL}}" data-href="?a=terms&b=about">
    @terms_about_label@
</a> - 

<a href="{{CONTACT_PAGE_URL}}" data-href="?a=terms&b=contact">
    @terms_contact_label@
</a> - 

<a href="{{PRIVACY_PAGE_URL}}" data-href="?a=terms&b=privacy">
    @terms_privacy_label@
</a> - 

<a href="{{TOS_PAGE_URL}}" data-href="?a=terms&b=tos">
    @terms_tos_label@
</a> - 

<a href="{{DISCLAIMER_PAGE_URL}}" data-href="?a=terms&b=disclaimer">
    @terms_disclaimer_label@
</a> - 

<a href="{{DEVELOPERS_PAGE_URL}}" data-href="?a=terms&b=developers">
    @terms_developers_label@
</a> - 

<a href="{{ADMIN_URL}}">
    @admin_link_label@
</a>