<div class="li">
	<div class="floatLeft imageJar">
		<a href="{{LI_URL}}">
			<img src="{{LI_AVATAR}}" class="borderRadius100">
		</a>
	</div>

	<div class="floatLeft textJar">
		<strong>
			<a href="{{LI_URL}}" data-href="?a=timeline&id={{LI_USERNAME}}">{{LI_NAME}}</a>
		</strong>

		<small>@{{LI_USERNAME}}</small>
		
		<div class="btnJar">
			{{LI_BTN}}
		</div>
	</div>

	<div class="floatClear"></div>
</div>