<div class="userColumn suggestion_{{LIST_SEARCH_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_SEARCH_URL}}" data-href="?a=timeline&id={{LIST_SEARCH_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_SEARCH_THUMBNAIL_URL}}" alt="{{LIST_SEARCH_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_SEARCH_URL}}" data-href="?a=timeline&id={{LIST_SEARCH_USERNAME}}">{{LIST_SEARCH_NAME}}</a>
        </strong>

        <small>{{LIST_SEARCH_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_SEARCH_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>