<span class="like-activity activity-btn" onclick="getStoryReactions({{STORY_ID}});" title="@reactions_label@">
    <div class="reactionActivity">
    	<i class="fa fa-thumbs-up" data-visible="{{IS_STORY_LIKE}}"></i>
    	<i class="skemoji skemoji-heart" data-visible="{{IS_STORY_LOVE}}"></i>
    	<i class="skemoji skemoji-laughing" data-visible="{{IS_STORY_HAHA}}"></i>
    	<i class="skemoji skemoji-open-mouth" data-visible="{{IS_STORY_WOW}}"></i>
    	<i class="skemoji skemoji-cry" data-visible="{{IS_STORY_SAD}}"></i>
    	<i class="skemoji skemoji-rage" data-visible="{{IS_STORY_ANGRY}}"></i>
    </div>
    {{STORY_REACTIONS_NUM}}
</span>