<div class="timeline-buttons cover-resize-buttons">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="middle">
            <a onclick="SK_saveReposition();">
                <i class="fa fa-check"></i>
                @save_position_label@
            </a>
        </td>

        <td align="center" valign="middle">
            <a onclick="SK_cancelReposition();">
                <i class="fa fa-times"></i>
                @cancel@
            </a>
        </td>
    </tr>
    </table>
    <form class="cover-position-form hidden" method="post">
        <input class="cover-position" name="pos" value="0" type="hidden">
        <input class="screen-width" name="width" value="920" type="hidden">
        <input name="timeline_id" value="{{TIMELINE_ID}}" type="hidden">
    </form>
</div>

<div class="eventButtons timeline-buttons default-buttons">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="middle">
            <a onclick="eventAction('going');">
                <i class="fa fa-check"></i>
                @event_going_label@
            </a>
        </td>
        
        <td align="center" valign="middle">
            <a onclick="deleteEventWindow({{TIMELINE_ID}});">
                <i id="deleteEventIcon" class="fa fa-times"></i> 
                @delete_event_button@
            </a>
        </td>
    </tr>
    
    <tr>
        <td align="center" valign="middle">
            <a onclick="javascript:$('.cover-image-input').click();">
                <i class="fa fa-image"></i> 
                @change_cover_label@
            </a>
        </td>

        <td align="center" valign="middle">
            <a onclick="SK_repositionCover();">
                <i class="fa fa-arrows"></i> 
                @reposition_cover_label@
            </a>
        </td>
    </tr>
    </table>
</div>

<form class="cover-form hidden" method="post" enctype="multipart/form-data" action="{{CONFIG_REQUEST_SOURCE}}?t=cover&a=post_upload">
    <input class="cover-image-input hidden" type="file" name="image" accept="image/jpeg,image/png" onchange="javascript:$('form.cover-form').submit();">
    <input name="timeline_id" value="{{TIMELINE_ID}}" type="hidden">
</form>
<script>

function deleteEventWindow(timelineId)
{
    iconProgress($("#deleteEventIcon"));
    $.get(
        Sk_requestPath(),

        {
            t: 'user',
            timeline_id: timelineId,
            a: 'view_delete_event'
        },

        function(data)
        {
            iconProgress($("#deleteEventIcon"));
            if (data.status == 200)
            {
                $(document.body)
                    .append(data.html)
                    .css('overflow','hidden');
                
                if ($('#mainHeaderJar').width() < 920)
                {
                    $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
                }
            }
        }
    );
}
function deleteEvent(timelineId)
{
    $.get(
        Sk_requestPath(),

        {
            t: 'user',
            timeline_id: timelineId,
            a: 'delete_event'
        },

        function(data)
        {
            if (data.status == 200)
            {
                window.location = data.goto_url;
            }
        }
    );
}
</script>