<div class="welcomeFooter">
	<div class="floatLeft">
		<div class="footerLink">
			<a href="{{ABOUT_URL}}">About</a>
		</div>

		<i class="separator fa fa-circle"></i>

		<div class="footerLink">
			<a href="{{CONTACT_URL}}">Contact</a>
		</div>

		<i class="separator fa fa-circle"></i>

		<div class="footerLink">
			<a href="{{PRIVACY_URL}}">Privacy</a>
		</div>

		<i class="separator fa fa-circle"></i>

		<div class="footerLink">
			<a href="{{DISCLAIMER_URL}}">Disclaimer</a>
		</div>

		<i class="separator fa fa-circle"></i>

		<div class="footerLink">
			<a href="{{DEVELOPERS_URL}}">Developers</a>
		</div>

		<i class="separator fa fa-circle"></i>

		<div class="footerLink">
			<i class="fa fa-language"></i>

			<a>Languages <i class="fa fa-caret-up"></i></a>

			<div class="dropup dropupRight">{{LANGUAGES}}</div>
		</div>
	</div>

	<div class="floatRight">
		Copyright <i class="fa fa-copyright"></i> {{YEAR}} {{CONFIG_SITE_NAME}}. All rights reserved.
	</div>

	<div class="floatClear"></div>
</div>