<div class="userColumn suggestion_{{LIST_USER_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_USER_URL}}" data-href="?a=timeline&id={{LIST_USER_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_USER_THUMBNAIL_URL}}" alt="{{LIST_USER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_USER_URL}}" data-href="?a=timeline&id={{LIST_USER_USERNAME}}">{{LIST_USER_NAME}}</a>
        </strong>

        <small>{{LIST_USER_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_USER_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>