<div class="userColumn mypage_{{PAGE_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{PAGE_URL}}" data-href="?a=timeline&id={{PAGE_USERNAME}}">
            <img class="borderRadius100" src="{{PAGE_THUMBNAIL_URL}}" alt="{{PAGE_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{PAGE_URL}}" data-href="?a=timeline&id={{PAGE_USERNAME}}">{{PAGE_NAME}}</a>
        </strong>

        <small>{{PAGE_INFO}}</small>
    </div>

    <div class="floatClear"></div>
</div>