<div class="userColumn page-admin-{{LIST_LIKE_USER_ID}}" data-role="{{LIST_LIKE_USER_ROLE}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_LIKE_USER_URL}}" data-href="?a=timeline&id={{LIST_LIKE_USER_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_LIKE_USER_THUMBNAIL_URL}}" alt="{{LIST_LIKE_USER_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_LIKE_USER_URL}}" data-href="?a=timeline&id={{LIST_LIKE_USER_USERNAME}}">{{LIST_LIKE_USER_NAME}}</a>
        </strong>

        <small>{{LIST_LIKE_USER_INFO}}</small>
    </div>

    <div class="floatClear"></div>
</div>