<div class="popupColumnJar">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="40px" align="left" valign="middle">
            <a href="{{LIST_USER_URL}}">
                <img class="avatar" src="{{LIST_USER_THUMBNAIL_URL}}" width="32px" alt="{{LIST_USER_NAME}}">
            </a>
        </td>
        <td align="left" valign="middle">
            <a class="name" href="{{LIST_USER_URL}}">
                {{LIST_USER_NAME}}
            </a>
        </td>
        <td class="window-btn" align="right" valign="middle">
            {{LIST_USER_BUTTON}}
        </td>
    </tr>
    </table>
</div>