<div class="window-container">
    <div class="window-background" onclick="SK_closeWindow();"></div>

    <div class="reaction-wrapper">
        <div class="reaction-header-wrapper">
            <div class="reaction-header-tab selected-tab" title="{{INVITEACTIONS_TITLE}}">
                {{INVITEACTIONS_TITLE}}
            </div>

            <span class="reaction-close-btn" title="Close window" onclick="SK_closeWindow();">
                <i class="fa fa-remove"></i>
            </span>
        </div>

        <div class="reaction-content-wrapper">
            {{LIST_INVITEACTIONS}}
        </div>
    </div>
</div>