<div class="input-wrapper google-map-wrapper" data-group="B">
    <i class="fa fa-map-marker icon"></i>

    <input class="gmap-input" type="text" value="@post_publisher_googlemap_placeholder@" placeholder="@post_publisher_googlemap_placeholder@" data-placeholder="@post_publisher_googlemap_placeholder@" data-copy-to=".google-map-input">
    
    <input class="google-map-input" type="hidden" name="google_map_name" value="">
</div>