<span class="option photos" onclick="javascript:$('#storyPublisherJar').find('input.photo-upload-input').click();">
    <i class="ski-camera-add"></i>
</span>

<input class="photo-upload-input" type="file" name="photos[]" multiple="yes" accept="image/jpeg,image/png,image/gif" onchange="SK_writeStoryPhotoUpload(this);" style="height:1px;width:1px;overflow:hidden;margin-left:-999px;display:none;">