<a id="receiver-{{LIST_RECIPIENT_ID}}" class="userColumn cursorPointer" href="{{LIST_RECIPIENT_CONVO_URL}}">
    <div class="floatLeft imageJar">
        <img class="borderRadius100" src="{{LIST_RECIPIENT_THUMBNAIL_URL}}" alt="{{LIST_RECIPIENT_NAME}}">
    </div>

    <div class="floatLeft textJar">
        <strong>{{LIST_RECIPIENT_NAME}}</strong>
        <div class="newAlert">{{LIST_RECIPIENT_MESSAGES_COUNT}}</div>
    </div>

    <div class="floatClear"></div>
</a>