<li id="online_{{LIST_ONLINE_USER_ID}}">
    <a onclick="Sk_openChat({{LIST_ONLINE_USER_ID}},'{{LIST_ONLINE_USER_NAME}}','{{LIST_ONLINE_USERNAME}}');">
        <div class="onlineColumnJar">
            <div class="imageJar">
                <img src="{{LIST_ONLINE_USER_THUMBNAIL_URL}}" width="32px" height="32px">
                <div class="unread newAlert">{{LIST_ONLINE_USER_UNREAD}}</div>
            </div>
            <div class="timeJarA">
                <div class="timeJarB">
                    <div class="timeJarC">
                        {{ONLINE_STATUS_HTML}}
                    </div>
                </div>
            </div>
            <div class="nameJar">{{LIST_ONLINE_USER_NAME}}</div>
            <div class="clearJar"></div>
        </div>
    </a>
</li>