<div class="userColumn suggestion_{{LIST_GROUP_ID}}">
    <div class="floatLeft imageJar">
        <a href="{{LIST_GROUP_URL}}" data-href="?a=timeline&id={{LIST_GROUP_USERNAME}}">
            <img class="borderRadius100" src="{{LIST_GROUP_THUMBNAIL_URL}}" alt="{{LIST_GROUP_NAME}}">
        </a>
    </div>

    <div class="floatLeft textJar">
        <strong>
            <a href="{{LIST_GROUP_URL}}" data-href="?a=timeline&id={{LIST_GROUP_USERNAME}}">{{LIST_GROUP_NAME}}</a>
        </strong>

        <small>{{LIST_GROUP_INFO}}</small>
    </div>

    <div class="floatRight buttonJar">
        {{LIST_GROUP_BUTTON}}
    </div>

    <div class="floatClear"></div>
</div>