<div class="storyControls">
    <i class="fa fa-chevron-down cursorPointer" onclick="$('#story_{{STORY_ID}}').find('.controlBtns').fadeToggle('fast');"></i>
    <div class="controlBtns">
        {{BOOST_CONTROL}}
        {{PIN_CONTROL}}
    	{{SAVE_CONTROL}}
        {{NEW_TAB_CONTROL}}
        <hr>
        {{EDIT_CONTROL}}
        {{DELETE_CONTROL}}
        {{REPORT_CONTROL}}
    </div>
</div>