<div id="mainHeaderJar" name="top">
    <div id="mainHeaderContent">
        <div class="floatLeft">
            <a id="mainHeaderLogo" href="{{CONFIG_SITE_URL}}">
                <img id="miniLogo" src="{{CONFIG_THEME_URL}}/images/logo/tp-mini.png">
                <img id="maxLogo" src="{{CONFIG_THEME_URL}}/images/logo/tp-maxi.png" alt="{{CONFIG_SITE_NAME}}">
            </a>

            {{HEADER_SEARCH}}
        </div>

        <div class="floatRight">
            {{HEADER_NAVIGATION}}
        </div>

        <div class="floatClear"></div>
    </div>
</div>

{{HEADER_DROPDOWNS}}

<div id="pageLoadingBar"><dd></dd><dt></dt></div>