<div id="receiver-{{RECEIVER_ID}}" class="userColumn cursorPointer" onclick="Sk_openMessage({{RECEIVER_ID}},'{{RECEIVER_NAME}}','{{RECEIVER_USERNAME}}');" data-hover-active="1">
    <div class="floatLeft imageJar">
        <img class="borderRadius100" src="{{RECEIVER_THUMBNAIL_URL}}" alt="{{RECEIVER_NAME}}">
    </div>

    <div class="floatLeft textJar">
        <strong>{{RECEIVER_NAME}}</strong>
        <div class="newAlert">{{RECEIVER_UNREAD}}</div>
        <small class="msgPreview">{{RECEIVER_MESSAGE}}</small>
    </div>

    <div class="floatClear"></div>
</div>